//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.API.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CameraRequest
    {
        public int Id { get; set; }
        public int CameraID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> InCount { get; set; }
        public Nullable<int> OutCount { get; set; }
    
        public virtual Camera Camera { get; set; }
    }
}
